<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AirSpec extends Model
{
    protected $table = 'air_specs';
    protected $fillable = [
        'air_data_id',
        'air_s_1',
        'air_s_2',
        'air_s_3',
        'air_s_4',
        'air_s_5',
        'air_s_6',
        'air_s_7',
        'air_s_8',
        'air_s_9',
        'air_s_10',
        'air_s_11',
        'air_s_12',
        'air_s_13',
        'air_s_14',
        'air_s_15',
        'air_s_16',
        'air_s_17',
        'air_s_18',
        'air_s_19',
        'air_s_20',
        'air_s_21',
        'air_s_22',
        'air_s_23',
        'air_s_24',
        'air_s_25',
        'air_s_26',
        'air_s_27',
        'air_s_28',
        'air_s_29',
        'air_s_30',
        'air_s_31',
        'air_s_32',
        'air_s_33',
        'air_s_34',
        'air_s_35',
        'air_s_36',
        'air_s_37',
        'air_s_38',
        'air_s_39',
        'air_s_40',
        'air_s_41',
        'air_s_42',
        'air_s_43',
        'air_s_44',
        'air_s_45',
        'air_s_46',
        'air_s_47',
        'air_s_48',
        'air_s_49',
        'air_s_50',
        'air_s_51',
        'air_s_52',
        'air_s_53',
        'air_s_54',
        'air_s_55',
        'air_s_56',
        'air_s_57',
        'air_s_58',
        'air_s_59',
        'air_s_60',
        'air_s_61',
        'air_s_62',
        'user_id',
        'actby',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}
